name: build release test

on:
  push:
    branches:
      - main

jobs:
  build-Successful:
    runs-on: ubuntu-22.04
    steps:
    - name: print
      run: echo "Finished" 
  
  build-linux:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - uses: actions/cache@v4
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node

    - uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
            ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.101'

    - name: Publish Blogifier
      run: dotnet publish -c Release /p:RuntimeIdentifier=linux-x64 ./src/Blogifier/Blogifier.csproj --output dist
 
   build-Successful:
      runs-on: ubuntu-22.04
      steps:
      - name: print
        run: echo "Finished" 

    #- name: Add .nojekyll file
    #  run: touch dist/.nojekyll

    #- name: Deploy
    #  uses: JamesIves/github-pages-deploy-action@4.1.4
    #  with:
    #    branch: demo
    #    folder: release
